'use client';
import { useState } from 'react';
import { Database, GitBranch, Scissors, BookOpen } from 'lucide-react';
import { PageHeader, Panel, Notice } from './common';
import { format } from '@/lib/data';
import { gini } from '@/lib/gini';
export function Algorithm() {
  const [benign, setBenign] = useState(50), [malignant, setMalignant] = useState(50);
  const impurity = gini(benign, malignant), total = benign + malignant;
  return <>
    <PageHeader eyebrow="LEARN / CLASSIFICATION AND REGRESSION TREES" title="Hiểu CART từ một phép chia." description="Một cây nhị phân, những điều kiện dễ giải thích và một quy trình kiểm chứng bằng dữ liệu." />
    <div className="concept-intro"><div><span className="badge cyan">CART · BREIMAN ET AL., 1984</span><h2>Tách một vùng dữ liệu.<br />Lặp lại trên từng nhánh.</h2><p>CART là phương pháp học có giám sát cho phân loại và hồi quy. Ở mỗi node, cây tìm feature và threshold tạo mức giảm impurity lớn nhất, rồi chia thành hai nhánh.</p></div><div className="binary-demo"><span><Database size={18} />Dữ liệu tại node</span><strong>x<sub>j</sub> ≤ threshold?</strong><div><span>Đúng · nhánh trái</span><span>Sai · nhánh phải</span></div></div></div>
    <Panel title="Thử thay đổi phân bố lớp" subtitle="Ví dụ tổng hợp chỉ minh họa công thức Gini; độc lập hai thí nghiệm dataset thật"><div className="gini-demo"><div><label className="gini-slider">Số mẫu benign (0)<b>{benign}</b><input aria-label="Số mẫu benign" type="range" min="0" max="100" step="1" value={benign} onChange={e => setBenign(Number(e.target.value))} /></label><label className="gini-slider violet-slider">Số mẫu malignant (1)<b>{malignant}</b><input aria-label="Số mẫu malignant" type="range" min="0" max="100" step="1" value={malignant} onChange={e => setMalignant(Number(e.target.value))} /></label><div className="gini-distribution" role="img" aria-label="Tỷ lệ hai lớp"><div style={{ width: `${total ? benign/total*100 : 0}%` }} /><div style={{ width: `${total ? malignant/total*100 : 0}%` }} /></div><p className="chart-note">Tổng: {total} mẫu. Node thuần có Gini = 0; hai lớp cân bằng có Gini = 0,5.</p></div><div className="gini-value" aria-live="polite"><span>GINI IMPURITY</span><strong data-testid="gini-value">{impurity === null ? '—' : format(impurity,4)}</strong><code>G = 1 − p₀² − p₁²</code><p>{impurity === null ? 'Node rỗng: Gini không xác định.' : impurity === 0 ? 'Node thuần: mọi mẫu thuộc cùng một lớp.' : impurity === .5 ? 'Phân bố cân bằng: độ hỗn tạp lớn nhất của hai lớp.' : 'Phân bố chưa thuần: hai lớp cùng tồn tại.'}</p></div></div></Panel>
    <div className="two-columns"><Panel title="Classification Tree" subtitle="Dự báo lớp chiếm đa số tại lá"><div className="formula-card"><GitBranch size={22} /><code>G(t) = 1 − Σₖ pₖ²</code></div><p className="body-copy">Gini đo mức hỗn tạp của lớp. Cây chọn split làm giảm impurity có trọng số: ΔG = G(parent) − nL/n × G(left) − nR/n × G(right).</p><p className="body-copy">Tỷ lệ lớp tại lá bằng số mẫu train của từng lớp chia tổng mẫu tại lá. Đây là score của mô hình, chưa phải xác suất y tế được hiệu chuẩn. Khi hòa số mẫu hai lớp, scikit-learn chọn lớp có index nhỏ hơn.</p></Panel><Panel title="Regression Tree" subtitle="Dự báo trung bình target tại lá"><div className="formula-card violet"><GitBranch size={22} /><code>ŷ(t) = (1 / nₜ) Σᵢ∈ₜ yᵢ</code></div><p className="body-copy">Với squared_error, impurity tại node là MSE quanh mean của target. SSE = Σ(yᵢ − ŷ)²; MSE = SSE/n. Giảm weighted MSE tương đương giảm tổng SSE của hai nhánh.</p><p className="body-copy">Lá chứa nhiều mẫu cho một dự báo trung bình. Đầu ra không liên tục giữa các vùng và khó ngoại suy ngoài dữ liệu huấn luyện.</p></Panel></div>
    <Panel title="Từ cây phức tạp đến mô hình được kiểm chứng" subtitle="Huấn luyện và lựa chọn tham số là hai bước khác nhau"><div className="learning-flow">{[{ icon: GitBranch, title: '01 · Chia nhị phân', text: 'Binary Recursive Partitioning tìm split tốt nhất tại node. Đây là lựa chọn greedy cục bộ, không bảo đảm tối ưu toàn cục.' }, { icon: Scissors, title: '02 · Phạt độ phức tạp', text: 'Rα(T) = R(T) + α|L(T)|. R(T) là tổng impurity có trọng số tại lá; |L(T)| là số lá. Alpha càng lớn, cây càng bị cắt mạnh.' }, { icon: BookOpen, title: '03 · Chọn bằng CV', text: 'Chia train thành 5 folds. Mỗi lần fit 4 folds và đánh giá fold còn lại. Chọn alpha theo mean CV; khóa cấu hình trước khi đánh giá test.' }].map(c => <div key={c.title}><c.icon size={24} /><h3>{c.title}</h3><p>{c.text}</p></div>)}</div></Panel>
    <div className="two-columns"><Panel title="Đánh giá đúng điều gì?" subtitle="Metric phải đi cùng lớp, dataset và tập đánh giá"><div className="explanation-stack"><div><h3>Precision & recall của malignant</h3><p>Precision = TP/(TP+FP); recall = TP/(TP+FN). F1 là trung bình điều hòa của hai metric. Macro F1 coi mỗi lớp ngang nhau; weighted F1 theo số mẫu.</p></div><div><h3>MAE, RMSE & R²</h3><p>MAE = mean |y−ŷ|; RMSE = √mean(y−ŷ)². R² = 1−SSE/SST có thể âm khi mô hình kém hơn dự báo trung bình; RMSE phạt sai số lớn mạnh hơn MAE.</p></div><div><h3>ROC-AUC</h3><p>Đánh giá khả năng xếp hạng lớp positive theo score. Không chứng minh score đã hiệu chuẩn, không thay thế confusion matrix hay recall.</p></div></div></Panel><Panel title="Overfitting và giới hạn của CART" subtitle="Dễ giải thích không có nghĩa luôn chính xác"><div className="explanation-stack"><div><h3>Cây quá sâu có thể học nhiễu</h3><p>Train score tốt và CV/test score kém là dấu hiệu cần kiểm tra. Pruning và giới hạn độ sâu kiểm soát độ phức tạp.</p></div><div><h3>Cây nhạy với dữ liệu</h3><p>Thay đổi nhỏ của dữ liệu có thể đổi cấu trúc cây. Importance không chỉ ra quan hệ nhân quả.</p></div><div><h3>Ngăn data leakage</h3><p>Không chọn alpha bằng test. Tách tập trước các thao tác fit. Diabetes ở đây dùng dataset đã scale do scikit-learn cung cấp; chưa xây pipeline tiền xử lý cho dữ liệu lâm sàng mới.</p></div></div></Panel></div>
    <Panel title="CART, ID3 và C4.5" subtitle="So sánh các dạng thuật toán truyền thống"><div className="table-scroll" tabIndex={0} role="region" aria-label="Bảng dữ liệu có thể cuộn ngang"><table><caption className="sr-only">So sánh CART ID3 C4.5</caption><thead><tr><th>Tiêu chí</th><th>CART</th><th>ID3</th><th>C4.5</th></tr></thead><tbody><tr><td>Nhiệm vụ</td><td>Classification & regression</td><td>Classification</td><td>Classification</td></tr><tr><td>Chia node</td><td>Luôn nhị phân</td><td>Thường nhiều nhánh cho categorical</td><td>Nhị phân với continuous; đa nhánh categorical</td></tr><tr><td>Tiêu chí phổ biến</td><td>Gini / squared_error</td><td>Information gain</td><td>Gain ratio</td></tr><tr><td>Cắt tỉa</td><td>Cost-complexity pruning</td><td>Không có pruning trong bản gốc</td><td>Error-based pruning</td></tr><tr><td>Continuous features</td><td>Threshold splits</td><td>Cần xử lý thêm trong bản gốc</td><td>Threshold splits</td></tr></tbody></table></div><p className="chart-note">Ứng dụng sử dụng CART tối ưu hóa trong scikit-learn. Triển khai này yêu cầu dữ liệu số, không tự xử lý biến categorical thô.</p></Panel>
    <Notice>Trong DSS: dữ liệu → dự báo → giải thích → diễn giải → quyết định của con người. Decision Path giải thích đường đi của một mẫu trong cây, không chứng minh quan hệ nhân quả hay xác nhận quyết định đúng trong thực tế.</Notice>
    <Panel title="Tài liệu tham khảo" subtitle="Nguồn thuật toán và dữ liệu"><ul className="sources"><li>Breiman, L., Friedman, J. H., Olshen, R. A., & Stone, C. J. (1984). <i>Classification and Regression Trees.</i> Wadsworth.</li><li>Quinlan, J. R. (1986). Induction of Decision Trees. <i>Machine Learning, 1</i>, 81–106. <a href="https://doi.org/10.1007/BF00116251" target="_blank" rel="noreferrer">DOI</a></li><li>Quinlan, J. R. (1993). <i>C4.5: Programs for Machine Learning.</i> Morgan Kaufmann.</li><li><a href="https://scikit-learn.org/stable/modules/tree.html" target="_blank" rel="noreferrer">scikit-learn · Decision Trees</a></li><li><a href="https://scikit-learn.org/stable/auto_examples/tree/plot_cost_complexity_pruning.html" target="_blank" rel="noreferrer">scikit-learn · Cost-complexity pruning</a></li><li><a href="https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_breast_cancer.html" target="_blank" rel="noreferrer">Breast Cancer dataset</a> · <a href="https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_diabetes.html" target="_blank" rel="noreferrer">Diabetes dataset</a></li></ul></Panel>
  </>;
}
