'use client';
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid, Legend, LineChart, Line, ScatterChart, Scatter, ReferenceLine, ErrorBar } from 'recharts';
import { Artifact } from '@/lib/types';
import { getModel, modelLabel } from '@/lib/data';
const grid = 'var(--border)';
const tooltip = { background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 10, color: 'var(--text)' };
const axis = { fill: 'var(--muted)', fontSize: 12 };
export function ComparisonChart({ a }: { a: Artifact }) {
  const data = a.models.filter(m => [a.baseline, a.selected, a.report_model].includes(m.id)).map(m => ({ name: m.id === a.baseline ? 'Baseline' : m.id === a.selected ? 'CV selected' : 'α = ' + Number(m.alpha.toPrecision(6)), train: a.task === 'classification' ? m.train_metrics.accuracy * 100 : m.train_metrics.rmse, test: a.task === 'classification' ? m.metrics.accuracy * 100 : m.metrics.rmse }));
  return <div className="chart" role="img" aria-label={`So sánh ${a.task === 'classification' ? 'Accuracy (%)' : 'RMSE'} train và test`}><ResponsiveContainer width="100%" height="100%"><BarChart data={data} barGap={6}><CartesianGrid stroke={grid} vertical={false} strokeDasharray="3 5" /><XAxis dataKey="name" tick={axis} axisLine={false} tickLine={false} /><YAxis tick={axis} axisLine={false} tickLine={false} domain={a.task === 'classification' ? [0, 100] : [0, 'auto']} width={38} /><Tooltip contentStyle={tooltip} formatter={v => Number(v).toFixed(2)} /><Legend iconType="circle" wrapperStyle={{ fontSize: 13, paddingTop: 12 }} /><Bar isAnimationActive={false} dataKey="train" name="Train" fill="#818cf8" radius={[4, 4, 0, 0]} maxBarSize={38} /><Bar isAnimationActive={false} dataKey="test" name="Test" fill="#38bdf8" radius={[4, 4, 0, 0]} maxBarSize={38} /></BarChart></ResponsiveContainer></div>;
}
export function PruningChart({ a, kind }: { a: Artifact; kind: 'leaves' | 'depth' | 'cv' }) {
  const data = a.models.map(m => ({ label: String(m.alpha), value: kind === 'cv' ? m.cv.mean : m[kind], error: m.cv.std }));
  return <div className="chart" role="img" aria-label={`Alpha và ${kind}`}><ResponsiveContainer width="100%" height="100%"><LineChart data={data}><CartesianGrid stroke={grid} strokeDasharray="3 5" vertical={false} /><XAxis dataKey="label" tick={axis} axisLine={false} tickLine={false} interval="preserveStartEnd" minTickGap={35} /><YAxis tick={axis} axisLine={false} tickLine={false} width={42} domain={kind === 'cv' && a.task === 'classification' ? [0, 1] : [0, 'auto']} /><Tooltip contentStyle={tooltip} labelFormatter={label => `α = ${label}`} formatter={v => Number(v).toFixed(4)} /><Line isAnimationActive={false} dataKey="value" name={kind === 'cv' ? `CV ${a.cv_metric}` : kind === 'leaves' ? 'Số lá' : 'Độ sâu'} stroke={kind === 'cv' ? '#2dd4bf' : '#38bdf8'} strokeWidth={2.5} dot={{ r: 3, fill: 'var(--surface)', strokeWidth: 2 }} type="linear">{kind === 'cv' && <ErrorBar dataKey="error" width={3} stroke="#2dd4bf" />}</Line></LineChart></ResponsiveContainer></div>;
}
export function RegressionScatter({ a, id, residual = false }: { a: Artifact; id: string; residual?: boolean }) {
  const m = getModel(a, id);
  return <div className="chart" role="img" aria-label={residual ? 'Phần dư actual − predicted trên test' : 'Giá trị thực tế và dự báo trên test'}><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{ bottom: 20, right: 15 }}><CartesianGrid stroke={grid} strokeDasharray="3 5" /><XAxis dataKey={residual ? 'predicted' : 'actual'} type="number" tick={axis} axisLine={false} tickLine={false} name={residual ? 'Dự báo' : 'Thực tế'} label={{ value: residual ? 'Predicted' : 'Actual', position: 'insideBottom', offset: -15, fill: 'var(--muted)', fontSize: 12 }} /><YAxis dataKey={residual ? 'residual' : 'predicted'} type="number" tick={axis} name={residual ? 'Phần dư' : 'Dự báo'} width={45} axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltip} formatter={v => Number(v).toFixed(2)} cursor={{ strokeDasharray: '3 3' }} /><ReferenceLine {...(residual ? { y: 0 } : { segment: [{ x: 0, y: 0 }, { x: 350, y: 350 }] })} stroke="#818cf8" strokeDasharray="5 5" ifOverflow="extendDomain" /><Scatter isAnimationActive={false} data={m.evaluation} fill={residual ? '#818cf8' : '#38bdf8'} fillOpacity={.7} /></ScatterChart></ResponsiveContainer></div>;
}
export function RocChart({ a, id }: { a: Artifact; id: string }) { const m = getModel(a, id); return <div className="chart" role="img" aria-label="ROC curve trên test"><ResponsiveContainer width="100%" height="100%"><LineChart data={m.roc}><CartesianGrid stroke={grid} strokeDasharray="3 5" /><XAxis dataKey="fpr" type="number" domain={[0, 1]} tick={axis} name="False positive rate" /><YAxis domain={[0, 1]} tick={axis} width={40} /><Tooltip contentStyle={tooltip} /><ReferenceLine segment={[{ x: 0, y: 0 }, { x: 1, y: 1 }]} stroke="#818cf8" strokeDasharray="4 4" /><Line isAnimationActive={false} dataKey="tpr" name="True positive rate" stroke="#2dd4bf" type="stepAfter" strokeWidth={2} dot={false} /></LineChart></ResponsiveContainer></div>; }
export function ModelComparisonTable({ a }: { a: Artifact }) { return <div className="table-scroll" tabIndex={0} role="region" aria-label="Bảng dữ liệu có thể cuộn ngang"><table><caption className="sr-only">Kết quả test các mô hình {a.dataset}</caption><thead><tr><th>Mô hình</th><th>Alpha</th><th>Độ sâu</th><th>Lá</th><th>{a.task === 'classification' ? 'Accuracy' : 'RMSE'}</th><th>{a.task === 'classification' ? 'Macro F1' : 'R²'}</th></tr></thead><tbody>{a.models.filter(m => [a.baseline, a.selected, a.report_model].includes(m.id)).map(m => <tr key={m.id}><td>{modelLabel(a, m)}</td><td>{m.alpha}</td><td>{m.depth}</td><td>{m.leaves}</td><td>{a.task === 'classification' ? (m.metrics.accuracy * 100).toFixed(2) + '%' : m.metrics.rmse.toFixed(3)}</td><td>{(a.task === 'classification' ? m.metrics.macro_f1 : m.metrics.r2).toFixed(4)}</td></tr>)}</tbody></table></div>; }
