'use client';
import { useState } from 'react';
import { artifacts, getModel, format, percent, metadata } from '@/lib/data';
import { PageHeader, Panel, Metric, ModelPicker, ModelDetails, Importance, Notice } from './common';
import { ComparisonChart, RegressionScatter, RocChart, ModelComparisonTable } from './charts';
import { TreeView } from './tree-view';
import { Artifact, Model, Task } from '@/lib/types';
export function Lab({ task }: { task: Task }) {
  const a = artifacts[task], [id, setId] = useState(a.selected), m = getModel(a, id);
  const classification = task === 'classification';
  return <>
    <PageHeader eyebrow={classification ? 'EXPERIMENT 01 / CLASSIFICATION' : 'EXPERIMENT 02 / REGRESSION'} title={classification ? 'Phòng thí nghiệm phân loại' : 'Phòng thí nghiệm hồi quy'} description={classification ? 'Breast Cancer Wisconsin Diagnostic · Gini impurity · malignant = 1, benign = 0.' : 'Diabetes · squared_error · dự báo chỉ số tiến triển bệnh sau một năm trong dữ liệu nghiên cứu.'} />
    <div className="toolbar"><ModelPicker a={a} id={id} onChange={setId} /><span className="toolbar-note">Chọn artifact có sẵn · không huấn luyện trên trình duyệt</span></div>
    <ModelDetails a={a} m={m} />
    <div className="metrics-grid">{classification ? <><Metric title="Accuracy · test" value={percent(m.metrics.accuracy)} detail={`${a.test_count} mẫu holdout`} /><Metric title="Precision · malignant" value={percent(m.metrics.precision)} detail="Positive class = 1" /><Metric title="Recall · malignant" value={percent(m.metrics.recall)} detail="TP / (TP + FN)" accent="teal" /><Metric title="F1 · malignant" value={format(m.metrics.f1, 4)} detail={`Macro F1 ${format(m.metrics.macro_f1, 4)}`} accent="violet" /></> : <><Metric title="MAE · test" value={format(m.metrics.mae, 3)} detail="Sai số tuyệt đối trung bình" /><Metric title="MSE · test" value={format(m.metrics.mse, 3)} detail="Bình phương sai số trung bình" /><Metric title="RMSE · test" value={format(m.metrics.rmse, 3)} detail="Cùng đơn vị với target" accent="violet" /><Metric title="R² · test" value={format(m.metrics.r2, 4)} detail="So với baseline dự báo trung bình" accent="teal" /></>}</div>
    <Panel title={classification ? 'Classification Tree' : 'Regression Tree'} subtitle={`Cấu trúc thật · ${m.id} · ${a.version}`}><TreeView key={m.id} a={a} m={m} /></Panel>
    {classification ? <><div className="two-columns"><Panel title="Confusion Matrix" subtitle="Hàng: lớp thật · Cột: lớp dự báo · test holdout"><Confusion m={m} /><p className="chart-note">FN = malignant được dự báo benign. Recall và precision đều xét malignant = 1.</p></Panel><Panel title="ROC curve" subtitle={`ROC-AUC test = ${format(m.metrics.roc_auc, 4)} · Positive = malignant`}><RocChart a={a} id={id} /><p className="chart-note">Điểm số là tỷ lệ malignant tại lá; chưa hiệu chuẩn thành xác suất lâm sàng.</p></Panel></div><Panel title="Classification report" subtitle={`Macro F1 ${format(m.metrics.macro_f1, 4)} · Weighted F1 ${format(m.metrics.weighted_f1, 4)}`}><Report a={a} m={m} /></Panel></> : <><div className="two-columns"><Panel title="Actual vs Predicted" subtitle="89 mẫu test · đường nét đứt y = x"><RegressionScatter a={a} id={id} /></Panel><Panel title="Residual Plot" subtitle="Phần dư = actual − predicted · test holdout"><RegressionScatter a={a} id={id} residual /></Panel></div><Notice>Tại một lá, CART hồi quy dự báo trung bình target của các mẫu train ở lá đó. Dự báo là hàm hằng từng vùng, không ngoại suy tốt ngoài dữ liệu đã học.</Notice></>}
    <div className="two-columns"><Panel title="Feature importance" subtitle="8 đặc trưng có mức giảm impurity cao nhất"><Importance a={a} m={m} /></Panel><Panel title="Baseline và mô hình cắt tỉa" subtitle={classification ? 'Accuracy (%) · train / test' : 'RMSE · train / test · thấp hơn là tốt hơn'}><ComparisonChart a={a} /><p className="chart-note">Alpha lớn hơn phạt số lá mạnh hơn. CV trên train chọn mô hình; test chỉ dùng đánh giá sau khi khóa lựa chọn.</p></Panel></div>
    <Panel title="Kết quả đối chiếu" subtitle={`${a.dataset} · cùng phép chia dữ liệu`}><ModelComparisonTable a={a} /></Panel>
    <p className="artifact-note">{metadata.version} · 5-fold CV ({a.cv_metric}) = {format(m.cv.mean, 4)} ± {format(m.cv.std, 4)} (SD giữa folds).</p>
  </>;
}
function Confusion({ m }: { m: Model }) { const c = m.confusion!; return <div className="confusion" tabIndex={0} role="region" aria-label="Ma trận nhầm lẫn có thể cuộn ngang"><div className="confusion-axis">Dự báo</div><table><caption className="sr-only">Confusion matrix test, labels 0 benign và 1 malignant</caption><thead><tr><th scope="col">Thực tế</th><th scope="col">benign (0)</th><th scope="col">malignant (1)</th></tr></thead><tbody><tr><th scope="row">benign (0)</th><td className="correct">{c[0][0]}<small>TN</small></td><td className="incorrect">{c[0][1]}<small>FP</small></td></tr><tr><th scope="row">malignant (1)</th><td className="incorrect">{c[1][0]}<small>FN</small></td><td className="correct">{c[1][1]}<small>TP</small></td></tr></tbody></table></div>; }
function Report({ a, m }: { a: Artifact; m: Model }) { return <div className="table-scroll" tabIndex={0} role="region" aria-label="Bảng dữ liệu có thể cuộn ngang"><table><caption className="sr-only">Classification report trên test {a.dataset}</caption><thead><tr><th>Lớp / trung bình</th><th>Precision</th><th>Recall</th><th>F1</th><th>Support</th></tr></thead><tbody>{['benign','malignant','macro avg','weighted avg'].map(label => { const r = m.report![label] as Record<string, number>; return <tr key={label}><td>{label}</td><td>{format(r.precision, 4)}</td><td>{format(r.recall, 4)}</td><td>{format(r['f1-score'], 4)}</td><td>{r.support}</td></tr>; })}</tbody></table></div>; }
