'use client';
import Link from 'next/link';
import { GitBranch, Database, Crosshair, Activity, FlaskConical, Braces, UserRound, Route, Scissors, BookOpen, ArrowUpRight } from 'lucide-react';
import { artifacts, getModel, metadata, percent, format } from '@/lib/data';
import { PageHeader, Panel, Metric } from './common';
import { Button } from './ui/button';
import { ComparisonChart, ModelComparisonTable } from './charts';
const a = artifacts.classification, r = artifacts.regression;
const c = getModel(a), reg = getModel(r);
export function Overview() {
  return <>
    <PageHeader eyebrow="CART / RESEARCH WORKSPACE" title="Từ dữ liệu đến quyết định." description="Khám phá cây quyết định, kiểm chứng mô hình và hiểu từng bước suy luận." action={<Button asChild><Link href="/prediction"><FlaskConical size={17} />Bắt đầu trải nghiệm</Link></Button>} />
    <div className="overview-banner"><div><span className="badge cyan">CLASSIFICATION & REGRESSION</span><h2>Một thuật toán.<br /><span>Hai cách nhìn dữ liệu.</span></h2><p>CART chia dữ liệu qua các điều kiện nhị phân. Mỗi đường đi dẫn đến một dự báo có thể giải thích.</p><div className="banner-tags"><span><Database size={15} />1.011 mẫu nghiên cứu</span><span><GitBranch size={15} />{a.models.length + r.models.length} cấu hình đã huấn luyện</span></div></div><div className="tree-motif" aria-hidden="true"><div className="motif-node motif-root"><GitBranch size={18} /><span>DATA</span><b>Binary split</b></div><div className="motif-branches"><div className="motif-node"><span>CLASSIFICATION</span><b>Gini impurity</b><span className="motif-stat">569 mẫu · 30 features</span></div><div className="motif-node violet"><span>REGRESSION</span><b>Squared error</b><span className="motif-stat">442 mẫu · 10 features</span></div></div></div></div>
    <div className="section-label"><h2>Kết quả thực nghiệm</h2><span>Mô hình được chọn bằng 5-fold CV · Đánh giá trên test</span></div>
    <div className="metrics-grid"><Metric title="Classification · Accuracy" value={percent(c.metrics.accuracy)} detail={`Breast Cancer · ${a.test_count} mẫu test · α ${c.alpha}`} icon={<Crosshair size={20} />} /><Metric title="Classification · Macro F1" value={format(c.metrics.macro_f1, 4)} detail={`Gini · sâu ${c.depth} · ${c.leaves} nút lá`} icon={<GitBranch size={20} />} accent="teal" /><Metric title="Regression · RMSE" value={format(reg.metrics.rmse, 3)} detail={`Diabetes · ${r.test_count} mẫu test · α ${reg.alpha}`} icon={<Activity size={20} />} accent="violet" /><Metric title="Regression · R²" value={format(reg.metrics.r2, 4)} detail={`MAE ${format(reg.metrics.mae, 3)} · ${reg.leaves} nút lá`} icon={<Braces size={20} />} accent="blue" /></div>
    <div className="two-columns"><Panel title="Độ chính xác trước & sau cắt tỉa" subtitle="Breast Cancer · Accuracy (%) trên train và test" action={<Link className="text-link" href="/classification">Xem thí nghiệm <ArrowUpRight size={15} /></Link>}><ComparisonChart a={a} /></Panel><Panel title="Hai bộ dữ liệu, hai nhiệm vụ" subtitle="Dữ liệu chuẩn từ scikit-learn"><div className="dataset-row"><span className="dataset-icon"><GitBranch size={21} /></span><div><h3>Breast Cancer Wisconsin</h3><p>Phân loại · benign = 0 / malignant = 1</p></div><b>569<span>mẫu</span></b></div><div className="dataset-facts"><span><b>30</b> đặc trưng</span><span><b>455 / 114</b> train / test</span><span>Stratified split</span></div><div className="dataset-row"><span className="dataset-icon violet"><Activity size={21} /></span><div><h3>Diabetes</h3><p>Hồi quy · mức tiến triển sau một năm</p></div><b>442<span>mẫu</span></b></div><div className="dataset-facts"><span><b>10</b> đặc trưng</span><span><b>353 / 89</b> train / test</span><span>Random state 42</span></div><p className="chart-note">Diabetes dùng đặc trưng đã được scale trong dataset. Kết quả chỉ phục vụ nghiên cứu.</p></Panel></div>
    <Panel title="CART trong hệ hỗ trợ quyết định" subtitle="Mô hình đưa ra bằng chứng; con người đưa ra quyết định."><div className="dss-flow">{[{ icon: Database, title: 'Dữ liệu', text: 'Dataset & schema' }, { icon: GitBranch, title: 'Dự báo', text: 'Cây CART đã train' }, { icon: Route, title: 'Giải thích', text: 'Decision path' }, { icon: BookOpen, title: 'Diễn giải', text: 'Xem giới hạn mô hình' }, { icon: UserRound, title: 'Con người', text: 'Quyết định cuối cùng' }].map((s, i) => <div className="dss-step" key={s.title}><span className="step-index">0{i + 1}</span><s.icon size={23} /><h3>{s.title}</h3><p>{s.text}</p></div>)}</div></Panel>
    <div className="two-columns"><Panel title="Đối chiếu mô hình" subtitle="Classification · test holdout"><ModelComparisonTable a={a} /></Panel><Panel title="Tiếp tục khám phá" subtitle="Hiểu kết quả từ bên trong cây"><div className="quick-links">{[{ href: '/decision-path', icon: Route, title: 'Theo dấu một dự báo', text: 'Xem điều kiện IF–THEN tại từng node' }, { href: '/pruning', icon: Scissors, title: 'Thử nghiệm cost-complexity', text: 'Quan sát alpha, độ sâu và cross-validation' }, { href: '/algorithm', icon: BookOpen, title: 'Hiểu Gini qua tương tác', text: 'Thay đổi phân bố lớp và quan sát impurity' }].map(q => <Link key={q.href} href={q.href}><q.icon size={20} /><div><strong>{q.title}</strong><p>{q.text}</p></div><ArrowUpRight size={16} /></Link>)}</div></Panel></div>
    <p className="artifact-note">Model artifacts <code>{metadata.version}</code> · scikit-learn {metadata.sklearn} · float32 inference</p>
  </>;
}
